// Copies woff2 files for the curated bundled fonts out of the installed
// @fontsource packages and into apps/web/public/fonts, then generates the
// @font-face CSS. Exported images use ONLY these bundled fonts.
//
// Keep this list in lockstep with packages/shared/src/fonts.ts (BUNDLED_FONTS).
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { existsSync, mkdirSync, copyFileSync, writeFileSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const webNodeModules = resolve(root, 'apps/web/node_modules');
const outDir = resolve(root, 'apps/web/public/fonts');
const cssOut = resolve(root, 'apps/web/app/fonts.generated.css');

const FONTS = [
  { slug: 'inter', family: 'Inter', weights: [400, 500, 600, 700] },
  { slug: 'montserrat', family: 'Montserrat', weights: [400, 600, 700] },
  { slug: 'poppins', family: 'Poppins', weights: [400, 500, 600, 700] },
  { slug: 'roboto', family: 'Roboto', weights: [400, 500, 700] },
  { slug: 'open-sans', family: 'Open Sans', weights: [400, 600, 700] },
  { slug: 'lato', family: 'Lato', weights: [400, 700] },
  { slug: 'work-sans', family: 'Work Sans', weights: [400, 600, 700] },
  { slug: 'raleway', family: 'Raleway', weights: [400, 600, 700] },
  { slug: 'nunito', family: 'Nunito', weights: [400, 600, 700] },
  { slug: 'archivo', family: 'Archivo', weights: [400, 600, 700] },
  { slug: 'oswald', family: 'Oswald', weights: [400, 600, 700] },
  { slug: 'bebas-neue', family: 'Bebas Neue', weights: [400] },
  { slug: 'playfair-display', family: 'Playfair Display', weights: [400, 600, 700] },
  { slug: 'merriweather', family: 'Merriweather', weights: [400, 700] },
  { slug: 'lora', family: 'Lora', weights: [400, 600, 700] },
  { slug: 'source-serif-4', family: 'Source Serif 4', weights: [400, 600, 700] },
];

// node_modules dirs to search, in priority order: the web app's own, then this
// checkout's and every ANCESTOR's node_modules. Walking up matters for git
// worktrees, whose deps are hoisted to the primary checkout's node_modules — a
// worktree's own node_modules is partial and won't contain @fontsource.
function nodeModulesBases() {
  const bases = [webNodeModules];
  let dir = root;
  for (;;) {
    bases.push(resolve(dir, 'node_modules'));
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return bases;
}
const NM_BASES = nodeModulesBases();

function sourcePath(slug, weight) {
  // npm workspaces may hoist to root node_modules or keep it in the web app's;
  // git worktrees resolve to an ancestor's node_modules.
  const rel = `@fontsource/${slug}/files/${slug}-latin-${weight}-normal.woff2`;
  for (const base of NM_BASES) {
    const p = resolve(base, rel);
    if (existsSync(p)) return p;
  }
  return null;
}

mkdirSync(outDir, { recursive: true });

const faces = [];
let copied = 0;
let missing = 0;

for (const font of FONTS) {
  for (const weight of font.weights) {
    const src = sourcePath(font.slug, weight);
    const destName = `${font.slug}-${weight}.woff2`;
    const dest = resolve(outDir, destName);
    if (!src) {
      missing++;
      console.warn(`[fonts] missing source for ${font.family} ${weight} (skipped)`);
      continue;
    }
    copyFileSync(src, dest);
    copied++;
    faces.push(
      `@font-face {\n` +
        `  font-family: '${font.family}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${destName}') format('woff2');\n` +
        `}`,
    );
  }
}

const header = `/* AUTO-GENERATED by scripts/copy-fonts.mjs — do not edit. */\n`;
writeFileSync(cssOut, header + faces.join('\n') + '\n', 'utf8');

console.log(`[fonts] copied ${copied} woff2 file(s) → apps/web/public/fonts (${missing} missing)`);
console.log(`[fonts] wrote ${cssOut}`);
